#' GUIDetree-based AligNment ConficencE 2
#'
#' @param seq is the raw input sequences of class DNAbin (DNA) or SeqFastaAA (AA)
#' @param cutoff specifies a cutoff to remove unreliable columns below the cutoff
#' @title Alignment Confidence Scores with GUIDANCE
#' @description Assess uncertainty in multiple sequence aligment (MSA) with the
#'   GUIDANCE algorithm (Penn et al. 2010).
#' @param seqs An object of class \code{\link{DNAbin}} or \code{\link{AAbin}}
#'   containing unaligned sequences of DNA or amino acids.
#' @param cutoff specifies a cutoff to remove unreliable columns below the
#'   cutoff
#' @param parallel logical, if TRUE, specify the number of cores
#' @param ncore number of cores
#' @param bootstrap An integer giving the number of perturbated MSAs.
#' @param msa.program A charcter string giving the name of the MSA program,
#'   currelty either \code{"mafft"} (default) or\code{"prank"}.
#' @param exec A character string giving the path to the executable of the
#'   alignment program.
#' @param method further arguments passed to mafft, default is "auto"
#' @param mask specific residues below a certain cutoff are masked ('N' for DNA, 'X' for AA)
#'
#' @return alignment_score: is the GUIDANCE alignment score
#' @return GUIDANCE_residue_score
#' @return GUIDANCE_score: is the GUIDANCE column score
#' @return GUIDANCE_sequence_score
#' @return guidance_msa: is the base MSA removed from unreliable columns below
#'   cutoff
#' @return base_msa
#'
#' @details Calculates column unreliability by comparing alternative bootstrap
#'   MSAs (Felsenstein 1985) generated by different guide trees. Thus GUIDANCE
#'   is a measure for guide-tree uncertainty. The basic comparison between the
#'   BP MSAs and a reference MSA is if column residue pairs are identical in
#'   both MSAs.
#' @author Franz-Sebastian Krah
#' @references Felsenstein J. 1985. Confidence limits on phylogenies: an
#'   approach using the bootstrap. Evolution 39:783–791
#' @references Penn et al. (2010). An alignment confidence score capturing
#'   robustness to guide tree uncertainty. Molecular Biology and Evolution
#'   27:1759--1767
#'
#' @importFrom ips mafft
#' @import doSNOW
#' @import foreach
#' @import parallel
#' @import pbmcapply
#' @import plyr
#' @importFrom phangorn as.phyDat dist.ml
#'
#' @author Franz-Sebastian Krah
#' @author Christoph Heibl
#' @export


